scalar DateTime

type Query {
  getDateTime: DateTime!
}

type Entity {
  id: ID!
  createdAt: DateTime
  updatedAt: DateTime
}

type Pagination {
  page: Int!
  perPage: Int!
  total: Int!
}

enum ROLE_ENUM {
  ADMIN
  ATC
  SALES
  COMMERCE
}
