scalar DateTime
scalar File

type Entity {
  id: ID!
  createdAt: DateTime
  updatedAt: DateTime
}

interface Pagination {
  page: Int!
  perPage: Int!
  total: Int
}

enum Role {
  ADMIN
  ATC
  SALES
  COMMERCE
}

enum Region {
  CENTER
  CENTER_EAST
  NORTH_WEST
  FAR_WEST
  NORTH_EAST
  SOUTH_EAST
  FAR_EAST
  DEV_ZONE_SOUTH
}

enum ProductType {
  LIQUID
  SOLID
  GAS
}

type Query {
  getDateTime: DateTime!
}

type Mutation {
  randomize: Float!
  readTextFile(file: File!): String!
  saveFile(file: File!): Boolean!
}

type Subscription {
  testConnection: Int!
  randomNumber: Float!
}
