type Order {
  id: Int!
  items: [OrderItem!]!
  client: Client!
  createdAt: DateTime!
  updatedAt: DateTime!
}

type OrderItem {
  product: Product!
  quantity: Float!
}

type OrdersList implements Pagination {
  orders: [Order]!
  page: Int!
  perPage: Int!
  total: Int!
}

input OrderItemInput {
  productId: Int!
  quantity: Float!
}

input CreateOrderInput {
  clientId: Int!
  userId: Int!
  items: [OrderItemInput!]!
}

type Query {
  listOrders(page: Int!, perPage: Int!): OrdersList!
  getOrder(id: Int!): Order
}

type Mutation {
  createOrder(orderInfo: CreateOrderInput!): Order!
}

# type Subscription {
#   orderOrders: [OrderOrdersOutput!]!
# }
