type Query {
  getSession: User
}

type Mutation {
  login(email: String!, password: String!): User
  logout: Boolean
  forgotPassword(email: String!): String
  resetPassword(newPassword: String!, token: String!): Boolean
  confirmEmail(token: String!): Boolean
}
