type AuthResponse {
  token: String!
}

type Mutation {
  login(email: String!, password: String!): AuthResponse
  # logout: Boolean
  # resetPassword(newPassword: String!): Boolean
  confirmEmail(token: String!): Boolean
}
