input AuthInput {
  email: String!
  password: String!
}

type AuthResponse {
  token: String!
}

type Mutation {
  # login(credentials: AuthInput): AuthResponse
  # logout: Boolean
  # resetPassword(newPassword: String!): Boolean
  confirmEmail(token: String!): Boolean
}
