//Errors
export const ERRORS = {
  UNKNOWN_ERROR: "UNKNOWN_ERROR",
  INVALID_INPUT_ERROR: "INVALID_INPUT_ERROR",
  USER_EXISTS_ERROR: "USER_EXISTS_ERROR",
};

export const DELAYS = {
  SESSION_EXPIRATION_TIME: Number(process.env.SESSION_EXPIRATION_TIM),
  EMAIL_CONFIRMATION_EXPIRATION_TIME: Number(process.env.EMAIL_CONFIRMATION_EXPIRATION_TIME),
};
