type Product {
  id: Int!
  type: String!
  quantity: Float!
  points: Int!
  active: Boolean!
  createdAt: DateTime!
  updatedAt: DateTime!
}

type ProductsList implements Pagination {
  products: [Product]!
  page: Int!
  perPage: Int!
  total: Int!
}

input CreateProductInput {
  type: String!
  quantity: Float!
  points: Int!
  active: Boolean
}

input UpdateProductInput {
  type: String
  quantity: Float
  points: Int
  active: Boolean
}

type Query {
  listProducts(page: Int!, perPage: Int!): ProductsList!
  getProduct(id: ID!): Product
}

type Mutation {
  createProduct(productInfo: CreateProductInput!): Product!
  updateProduct(id: ID!, productInfo: UpdateProductInput!): Boolean!
  deleteProduct(id: ID!): Boolean!
}
